### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkvmtkSegmentationPython'

### ISSUE THREAD

**Issue by upupming** [vmtk/SlicerExtension-VMTK#39]
When using the LevelSet Segmentation, I got the following error:

```py
Unable to import the SlicerVmtk libraries
Traceback (most recent call last):
  File "C:/Users/ming/projects/SlicerExtension-VMTK/LevelSetSegmentation/LevelSetSegmentation.py", line 288, in onPreviewButtonClicked
    self.start(True)
  File "C:/Users/ming/projects/SlicerExtension-VMTK/LevelSetSegmentation/LevelSetSegmentation.py", line 500, in start
    'collidingfronts'))
  File "C:/Users/ming/projects/SlicerExtension-VMTK/LevelSetSegmentation/LevelSetSegmentation.py", line 706, in performInitialization
    collidingFronts = vtkvmtkSegmentation.vtkvmtkCollidingFrontsImageFilter()
UnboundLocalError: local variable 'vtkvmtkSegmentation' referenced before assignment
```

**Comment by lassoan** [comment]
It works well for me on Windows with a recent Slicer Preview Release (I had to change an xrange to range).

Have you installed VMTK extension from the Extension manager?
What operating system and Slicer version do you use?

**Comment by upupming** [comment]
> Does it work well in the latest Slicer Preview Release (after changing xrange to range)?

Yes, it works on Windows after change `xrange` to `range` on the 20210226 version.

I found the path to the `vtkvmtkSegmentationPython` module is `C:/Users/ming/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/SlicerVMTK/lib/Slicer-4.11/qt-loadable-modules\\vtkvmtkSegmentationPython.pyd` on Windows:
![image](https://user-images.githubusercontent.com/24741764/130821421-bcc9b7b4-62c5-40cc-8c04-f557f1738d08.png)

But on macOS, it doesn't exist, this may be the root cause of the error:

![image](https://user-images.githubusercontent.com/24741764/130821538-18bb9116-8f54-4e8e-a0a8-6df72ef4352d.png)
